version: '3'
services:
  postgres:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: 
      DATABASE_URL:
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local
